<?php

namespace AppBundle\Repository;

/**
 * GolesXPartidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GolesXPartidoRepository extends \Doctrine\ORM\EntityRepository
{
}
