<?php

namespace AppBundle\Repository;

/**
 * TarjetasXPartidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarjetasXPartidoRepository extends \Doctrine\ORM\EntityRepository
{
}
