<?php

namespace AppBundle\Repository;

/**
 * EstadioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadioRepository extends \Doctrine\ORM\EntityRepository
{
}
