## To get started with security, check out the documentation:
## https://symfony.com/doc/current/security.html
#security:
#
#    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
#    providers:
#        in_memory:
#            memory: ~
#
#    firewalls:
#        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        main:
#            anonymous: ~
#            # activate different ways to authenticate
#
#            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
#            #http_basic: ~
#
#            # https://symfony.com/doc/current/security/form_login_setup.html
#            #form_login: ~

# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$1BloGFHCUpnYbGn1umxCHe9TsVte2tTZ5ErHc7ikxYRB4dzjMqK6K
                        roles: 'ROLE_ADMIN'
        fos_userbundle:
            id: fos_user.user_provider.username



    firewalls:
        admin:
            pattern: ^/admin
            logout:       true
            anonymous: ~
            http_basic: ~
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous: ~


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
#        - { path: ^/equipo, role: ROLE_ADMIN }
#        - { path: ^/partido, role: ROLE_ADMIN }
#        - { path: ^/jugador, role: ROLE_ADMIN }
#        - { path: ^/tarjetas, role: ROLE_ADMIN }
#        - { path: ^/goles, role: ROLE_ADMIN }


